package visao;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author cassio
 */
public class ProdutosViagens extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProdutosViagens
     */
    public ProdutosViagens() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnProduto = new javax.swing.JPanel();
        jlbDestinoPassagem = new javax.swing.JLabel();
        jlbPrecoPassagem = new javax.swing.JLabel();
        jbtnReservarPassagem = new javax.swing.JButton();

        jpnProduto.setPreferredSize(new java.awt.Dimension(260, 120));

        jlbDestinoPassagem.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbDestinoPassagem.setText("--------------destino-------------------");
        jlbDestinoPassagem.setPreferredSize(new java.awt.Dimension(190, 28));
        jlbDestinoPassagem.setRequestFocusEnabled(false);

        jlbPrecoPassagem.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbPrecoPassagem.setText("R$ preco");
        jlbPrecoPassagem.setPreferredSize(new java.awt.Dimension(130, 28));
        jlbPrecoPassagem.setRequestFocusEnabled(false);

        jbtnReservarPassagem.setText("reservar");
        jbtnReservarPassagem.setMinimumSize(new java.awt.Dimension(86, 48));
        jbtnReservarPassagem.setPreferredSize(new java.awt.Dimension(86, 48));
        jbtnReservarPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReservarPassagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnProdutoLayout = new javax.swing.GroupLayout(jpnProduto);
        jpnProduto.setLayout(jpnProdutoLayout);
        jpnProdutoLayout.setHorizontalGroup(
            jpnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbDestinoPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbPrecoPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnReservarPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnProdutoLayout.setVerticalGroup(
            jpnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDestinoPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jpnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPrecoPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnReservarPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnReservarPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReservarPassagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnReservarPassagemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnReservarPassagem;
    private javax.swing.JLabel jlbDestinoPassagem;
    private javax.swing.JLabel jlbPrecoPassagem;
    private javax.swing.JPanel jpnProduto;
    // End of variables declaration//GEN-END:variables
}
